Import dependecy

In [3]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

Data collecton and preprocessing

In [4]:
#loading the dataset to pandas dataframe
load_dataset=pd.read_csv('loanprediction.csv')

In [5]:
type(load_dataset)

pandas.DataFrame

In [6]:
#printing the first 5 rows of the dataframe
load_dataset.head()

    Loan_ID Gender Married  ... Credit_History Property_Area Loan_Status
0  LP001002   Male      No  ...            1.0         Urban           Y
1  LP001003   Male     Yes  ...            1.0         Rural           N
2  LP001005   Male     Yes  ...            1.0         Urban           Y
3  LP001006   Male     Yes  ...            1.0         Urban           Y
4  LP001008   Male      No  ...            1.0         Urban           Y

[5 rows x 13 columns]

In [7]:

#number ofrowsand columns in the dataframe
load_dataset.shape

(614, 13)

In [8]:
#statistical measures about the dataset
load_dataset.describe()

       ApplicantIncome  CoapplicantIncome  ...  Loan_Amount_Term  Credit_History
count       614.000000         614.000000  ...         600.00000      564.000000
mean       5403.459283        1621.245798  ...         342.00000        0.842199
std        6109.041673        2926.248369  ...          65.12041        0.364878
min         150.000000           0.000000  ...          12.00000        0.000000
25%        2877.500000           0.000000  ...         360.00000        1.000000
50%        3812.500000        1188.500000  ...         360.00000        1.000000
75%        5795.000000        2297.250000  ...         360.00000        1.000000
max       81000.000000       41667.000000  ...         480.00000        1.000000

[8 rows x 5 columns]

In [9]:
#number of missing values in each column
load_dataset.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [10]:
#dropping the missing values
load_dataset=load_dataset.dropna()

In [11]:
#label encoding
load_dataset.replace({"Loan_Status":{'N':0,'Y':1}},inplace=True)

      Loan_ID  Gender Married  ... Credit_History Property_Area Loan_Status
1    LP001003    Male     Yes  ...            1.0         Rural           0
2    LP001005    Male     Yes  ...            1.0         Urban           1
3    LP001006    Male     Yes  ...            1.0         Urban           1
4    LP001008    Male      No  ...            1.0         Urban           1
5    LP001011    Male     Yes  ...            1.0         Urban           1
..        ...     ...     ...  ...            ...           ...         ...
609  LP002978  Female      No  ...            1.0         Rural           1
610  LP002979    Male     Yes  ...            1.0         Rural           1
611  LP002983    Male     Yes  ...            1.0         Urban           1
612  LP002984    Male     Yes  ...            1.0         Urban           1
613  LP002990  Female      No  ...            0.0     Semiurban           0

[480 rows x 13 columns]